name: Workflow Metrics v2
author: marcuslyons
description: Generate metrics for historical workflow runs
runs:
  using: 'docker'
  image: 'docker://ghcr.io/marcuslyons/workflow-metrics:v1'
branding:
  icon: 'rss'
  color: 'orange'
